# Generated by Django 3.2.13 on 2022-11-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOnBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=100)),
                ('discriminator', models.CharField(max_length=4)),
                ('total_break', models.IntegerField(default=0)),
                ('today_break', models.IntegerField(default=0)),
                ('total_input', models.IntegerField(default=0)),
                ('today_input', models.IntegerField(default=0)),
                ('is_resting', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remaining_rest_time', models.IntegerField(default=0)),
            ],
        ),
    ]
